### ISSUE TITLE
DatePicker is not working properly.

### ISSUE THREAD

**Issue by OdapX** [mdbootstrap/Bootstarters#11]
I'm trying to  add a date picker to my jsp , I have added Tailwind Elements CDN scripts as shown in the  Quick start documentation.
However **the Date picker** won't work instead it displays this :
<p align="center">
<img src="https://user-images.githubusercontent.com/72660683/149683550-a0dc0427-1f84-472c-91aa-aee57a48fef0.PNG"/>
</p>

**This is the original Element in the Docs :** 

> ![TailwindElement](https://user-images.githubusercontent.com/72660683/149683369-8ffa8f1a-df9c-4ad4-b678-cc30cfc059fb.PNG)

**This is my form :** 

> ![form](https://user-images.githubusercontent.com/72660683/149683477-8150da3e-5fc1-4b1c-8b49-5303add79c82.PNG)

**Head component :** 

> ![head](https://user-images.githubusercontent.com/72660683/149683486-bcbeba5b-37f5-4eb6-ad74-2f446e8cf903.PNG)

Tailwindcss is working just fine on my project the only problem is the datepicker Element. I don't know if that's matter but I'm using **tomcat** as a server .

**Comment by emorevival** [comment]
I had the same problem, after a lot of digging I found that the code they provide for us to copy is wrong, they missed the button that adds that calendar icon
![image](https://user-images.githubusercontent.com/32765662/149689290-e53a0241-766c-41d7-8881-175a3b234005.png)

**Comment by OdapX** [comment]
I don't know what's going on the website but in my case the button referring to the date picker is present in the  code  to copy : 

![aaabtn-date](https://user-images.githubusercontent.com/72660683/149695011-3357d615-4299-4441-9315-5e5be352d4f0.PNG)

I guess the issue I'm facing is concerning compatibility with the jsps .

**Comment by smolenski-mikolaj** [comment]
1. Have you installed the latest 1.0.0-alpha8 version?
2. Did you add the following configuration to your tailwind.config.js file?

```
module.exports = {
  content: ['./src/**/*.{html,js}', './node_modules/tw-elements/dist/js/**/*.js'],
  plugins: [
    require('tw-elements/dist/plugin')
  ]
}
```

Especially the content part with tw-elements js file is important, because some classes are added dynamically.

**Comment by OdapX** [comment]
As I mentioned, I am using  CDN  scripts, as the datepicker is the only element I want to use so I guess I don't have  to intall all the packages for that.

**Comment by smolenski-mikolaj** [comment]
@xvendor If You use CDN, in fact you use all of the styles and js without any optimization. 

Please add Font Awesome separately, it should fix the issue with toggle button:
```
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
```

**Comment by OdapX** [comment]
@smolenski-mikolaj  Yes in fact That works. I just needed to add the font Awesome library. Thanks for your help.
