### ISSUE TITLE
stepper component

### ISSUE THREAD

**Issue by jason-muriel** [mdbootstrap/Bootstarters#15]
The stepper does not resize for content that is retrieved via REST api. Is there a way to force the stepper to correctly display the content (height will fit content)? If you click between the steps then the stepper will display the content properly after the transition. Please let me know if there is a fix/workaround for this, thank you.

**Comment by smolenski-mikolaj** [comment]
There is an option to reload Stepper after fetching data. Please run this js code:

```
const oldStepper = Stepper.getInstance(myStepperEl);
stepperInstance.dispose();
const newStepper = new mdb.Stepper(myStepperEl);
```

myStepperEl is e.g. `document.getElementById(...)` or `document.getElementsByClassName(...)[0]`

**Comment by jason-muriel** [comment]
the code example gives error so I think you meant this?

myStepperEl = document.getElementById('editStepper');
const oldStepper = Stepper.getInstance(myStepperEl);
oldStepper.dispose;
const newStepper = new mdb.Stepper(myStepperEl);

but I get 'mdb is not defined' error now.

Thanks for your quick reply!

**Comment by smolenski-mikolaj** [comment]
It should be 

`const newStepper = new Stepper(myStepperEl);`

in the last line.

**Comment by jason-muriel** [comment]
works like a charm, just needed a second delay.  Thank you for the assistance!
