### ISSUE TITLE
TimePicker, unformated labels

### ISSUE THREAD

**Issue by duzda** [mdbootstrap/Bootstarters#16]
Hello,

currently using the tw-elements verison 1.0.0-alpha10 and tailwindcss 3.0.19
The time picker component seems to be missing some important css, in the image below is the current behaviour (I just copied the demo from https://tailwind-elements.com/docs/standard/forms/timepicker/)

![Screenshot_2022-02-10-23-59-12](https://user-images.githubusercontent.com/25201406/153513187-ce0c39c3-6d83-428a-a422-fda8750a6dc0.png)

Then this image below is the expected behaviour, which also works on the demo page.

![Screenshot_2022-02-11-00-15-51](https://user-images.githubusercontent.com/25201406/153513287-29b5f6a4-e57c-4fd0-be7f-376e71274363.png)

This is the case for both, hours and minutes. I've tried to debug this problem, and some of the computed css is missing.
See this image, for the computed css of timepicker-time-tips-* of my own project.

![image](https://user-images.githubusercontent.com/25201406/153513739-7f857f87-c2d1-4011-a80c-465321596fb9.png)

And then this is the computed css of the demo page.

![image](https://user-images.githubusercontent.com/25201406/153513703-ff6043b2-64f6-480c-afb3-40bccd8ddb83.png)

This issue can be easily solved by implementing all the changes, I've created a few more styles that add all the missing features. This is absolutly not a complete list of all the missing styles, it's just a hotfix if anyone faces the same issue.

```
.timepicker-time-tips-hours, .timepicker-time-tips-minutes {
    position: absolute;
    height: 32px;
    width: 32px;
    align-items: center;
    justify-content: center;
    display: flex;
    text-align: center;
}

.timepicker-time-tips-hours.active, .timepicker-time-tips-minutes.active {
    background-color: transparent;
}
```

I don't think I will able to fix this issue by myself, also would appreciate if anyone else is able to reproduce this issue.

Also, it's totally possible that I'm just dumb and missed something when creating the project, in that case I apologise.

**Comment by smolenski-mikolaj** [comment]
Actually I can find the styles in both plugin and cdn stylesheet. Also our demo page is built the same way as in the instruction guide. Which mode of installation did you choose? Can you share the code of your app?

**Comment by duzda** [comment]
I see, this is probably a mistake on my side, as I didn't include the cdn stylesheet, I've thought it would somehow get spitted out in the output.css if I went with the NPM way of tailwind elements (https://tailwind-elements.com/quick-start/) and tailwind cli for tailwindcss (https://tailwindcss.com/docs/installation)

If it's mandary to include the cdn, feel free to close this issue, as it's resolved then.

If it's not, then here's as minimal setup as possible with the same result as above.

index.html
```
<!DOCTYPE html>
<html>
<head>
    <link href="../dist/output.css" rel="stylesheet">
</head>
<body>
<div class="flex justify-center">
  <div class="timepicker relative form-floating mb-3 xl:w-96" data-mdb-with-icon="false" id="input-toggle-timepicker">
    <input type="text"
      class="form-control block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
      placeholder="Select a date" data-mdb-toggle="input-toggle-timepicker" />
    <label for="floatingInput" class="text-gray-700">Select a time</label>
  </div>
</div>
<script src="../node_modules/tw-elements/dist/js/index.min.js"></script>
</body>
</html>
```

input.css
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

tailwind.config.js
```
module.exports = {
  content: ['./src/**/*.{html,js}', './node_modules/tw-elements/dist/js/**/*.js'],
  plugins: [
    require('tw-elements/dist/plugin')
  ]
}
```

The folder structure is as follows
```
.
├── dist
│   └── output.css
├──node_modules
│   └── ...
├── package.json
├── package-lock.json
├── src
│   ├── index.html
│   └── input.css
└── tailwind.config.js
```
