### ISSUE TITLE
No custom javascript 

### ISSUE THREAD

**Issue by Igirid** [mdbootstrap/Bootstarters#6]
It seems like custom Javascript (for components that require js) is missing from the official guide.

**Comment by smolenski-mikolaj** [comment]
The guide was updated: https://tailwind-elements.com/quick-start/

**Comment by joshualinog** [comment]
it breaks next-js because of a 'document' reference.

**Comment by joshualinog** [comment]
![image](https://user-images.githubusercontent.com/1839603/150017879-707bf88a-3062-4541-b747-f5bde39d0559.png)

**Comment by joshualinog** [comment]
![image](https://user-images.githubusercontent.com/1839603/150018498-3b09736e-4a2d-46c6-a7ba-b845b2f33937.png)

**Comment by joshualinog** [comment]
ended up using the cdn option in nextjs's _document.js:

![image](https://user-images.githubusercontent.com/1839603/150019649-aed620d8-a89e-4e8d-8b3a-ce2c44ef8449.png)

**Comment by joshualinog** [comment]
@smolenski-mikolaj i don't want to use the cdn, so help is still needed even with how you've updated the quick start. i'm using nextjs

**Comment by nonfungible-dev** [comment]
Just want to put in that I'm also running into the document issue with nextjs; @jajourda appreciate the workaround with the CDN for now.
